/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatCreateDialog: typeof import('./src/components/chat/ChatCreateDialog.vue')['default']
    ChatList: typeof import('./src/components/chat/ChatList.vue')['default']
    ChatQuizCard: typeof import('./src/components/chat/ChatQuizCard.vue')['default']
    ChatStamp: typeof import('./src/components/chat/ChatStamp.vue')['default']
    ChatStampPopup: typeof import('./src/components/chat/ChatStampPopup.vue')['default']
    ChatText: typeof import('./src/components/chat/ChatText.vue')['default']
    CommonHeader: typeof import('./src/components/common/CommonHeader.vue')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    CustomRouter: typeof import('./src/components/CustomRouter.vue')['default']
    CustomTable: typeof import('./src/components/CustomTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    QuestionDialog: typeof import('./src/components/QuestionDialog.vue')['default']
    QuestionnaireDialog: typeof import('./src/components/chat/QuestionnaireDialog.vue')['default']
    QuestionStamp: typeof import('./src/components/QuestionStamp.vue')['default']
    QuestionText: typeof import('./src/components/QuestionText.vue')['default']
    QuizCard: typeof import('./src/components/QuizCard.vue')['default']
    QuizDialog: typeof import('./src/components/QuizDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StampList: typeof import('./src/components/chat/StampList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
